name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io/nallachaitanya07
          username: nallachaitanya07
          password: Chaitanya@2022

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nallachaitanya07/contoso-website:latest
